/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Modelos.ConexionBD;
import Modelos.Vaca;
import java.sql.SQLException;
import javax.swing.DefaultListModel;

/**
 *
 * @author Lauta
 */
public class ListadoDeVacas extends javax.swing.JFrame {
    DefaultListModel modeloLista = new DefaultListModel();
    ConexionBD conexion = new ConexionBD();
    public ListadoDeVacas() {
        initComponents();
        ListaVacas.setModel(modeloLista);
        CargarVacas();
        X.setVisible(false);
        NoPerteneceAlPlantel.setVisible(false);
        Bien.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CodigoVaca = new javax.swing.JTextField();
        NoPerteneceAlPlantel = new javax.swing.JLabel();
        Bien = new javax.swing.JLabel();
        X = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TfRaza = new javax.swing.JTextField();
        TfPeso = new javax.swing.JTextField();
        TfLactancias = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaVacas = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Filtrado por codigo :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 150, 31));

        CodigoVaca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CodigoVaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CodigoVacaKeyReleased(evt);
            }
        });
        jPanel1.add(CodigoVaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 150, 30));

        NoPerteneceAlPlantel.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        NoPerteneceAlPlantel.setForeground(new java.awt.Color(255, 51, 51));
        NoPerteneceAlPlantel.setText("No pertenece al plantel");
        jPanel1.add(NoPerteneceAlPlantel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 220, 30));

        Bien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Bien.jpg"))); // NOI18N
        jPanel1.add(Bien, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        X.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Mal.png"))); // NOI18N
        jPanel1.add(X, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Raza");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 40, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Peso");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 40, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Lactancia");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 80, 20));

        TfRaza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(TfRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 30));

        TfPeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(TfPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 110, 30));

        TfLactancias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(TfLactancias, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 110, 30));

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 100, 30));

        jButton2.setText("Dar de baja");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajaVaca(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 110, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 480, 250));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Raza");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 40, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("Peso");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 50, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Codigo");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 60, 30));

        ListaVacas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaVacasValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(ListaVacas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 480, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BajaVaca(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajaVaca
        TfRaza.getText();
           TfLactancias.getText();
           TfPeso.getText();
           try{
            conexion.Conectar();
            conexion.setS(conexion.getConexion().createStatement());
            conexion.setRs(conexion.getS().executeQuery("SELECT * FROM plantel where vcod = '"+CodigoVaca.getText()+"'"));
            if(!conexion.getRs().next())
            {
               
            }else{
                    conexion.setRs(conexion.getS().executeQuery("delete from plantel where vcod = '"+CodigoVaca.getText()+"' "));
                    ListaVacas.setVisible(false);
                    CargarVacas();
                    ListaVacas.setVisible(true);
            }
             
        }catch(SQLException ex)
        {
            System.out.println(ex);
        }
           
    }//GEN-LAST:event_BajaVaca

    public void CargarVacas()
    {
       conexion.Conectar();
       try
       {
           conexion.setS(conexion.getConexion().createStatement());
           conexion.setRs(conexion.getS().executeQuery("SELECT * FROM plantel"));
           while(conexion.getRs().next()){
                Vaca vAux = new Vaca();
                float peso = conexion.getRs().getFloat(3);
                vAux.setVcod(conexion.getRs().getString("vcod"));
                vAux.setRaza(conexion.getRs().getString("raza"));
                vAux.setAñoDeNacimiento(conexion.getRs().getString("anio_nac"));
                vAux.setPeso(peso);
                modeloLista.addElement(vAux);               
                }  
           System.out.println(modeloLista.get(1));
       }catch(SQLException ex)
       {
           System.out.println(ex);
       }
    }
    
    private void Modificar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar
           TfRaza.getText();
           TfLactancias.getText();
           TfPeso.getText();
        try{
            conexion.Conectar();
            conexion.setS(conexion.getConexion().createStatement());
            conexion.setRs(conexion.getS().executeQuery("UPDATE plantel set raza = '"+TfRaza.getText()+"' , peso = '"+TfPeso.getText()+"', c_lactancia = '"+TfLactancias.getText()+"' where vcod = '"+CodigoVaca.getText()+"' "));    
        }catch(SQLException ex)
        {
            System.out.println(ex);
        }
         X.setVisible(false);
         NoPerteneceAlPlantel.setVisible(false);
         Bien.setVisible(false);
         TfRaza.setText("");
         TfLactancias.setText("");
         TfPeso.setText("");
         CodigoVaca.setText("");
    }//GEN-LAST:event_Modificar

    private void CodigoVacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CodigoVacaKeyReleased
       if(CodigoVaca.getText().length() == 6)
        {
            conexion.Conectar();
            try{
                conexion.setS(conexion.getConexion().createStatement());
                conexion.setRs(conexion.getS().executeQuery("SELECT * FROM plantel where vcod = '"+CodigoVaca.getText()+"'"));
                if(conexion.getRs().next())
                {
                    X.setVisible(false);
                    NoPerteneceAlPlantel.setVisible(false);
                    TfRaza.setText(conexion.getRs().getString("raza"));
                    TfLactancias.setText(conexion.getRs().getString("c_lactancia"));
                    TfPeso.setText(conexion.getRs().getString("peso"));
                    Bien.setVisible(true);
                }else{
                    X.setVisible(true);
                    NoPerteneceAlPlantel.setVisible(true);
                    Bien.setVisible(false);
                    TfRaza.setText("");
                    TfLactancias.setText("");
                    TfPeso.setText("");
                   
                }
                
            }catch(SQLException ex)
            {
                System.out.println(ex);
            }
            
        } 
    }//GEN-LAST:event_CodigoVacaKeyReleased

    private void ListaVacasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaVacasValueChanged
        int index= ListaVacas.getSelectedIndex();
        Vaca vAux=(Vaca)modeloLista.getElementAt(index);
        conexion.Conectar();
            try{
                conexion.setS(conexion.getConexion().createStatement());
                conexion.setRs(conexion.getS().executeQuery("SELECT * FROM plantel where vcod = '"+vAux.getVcod()+"'"));
                if(conexion.getRs().next())
                {
                    TfRaza.setText(conexion.getRs().getString("raza"));
                    TfLactancias.setText(conexion.getRs().getString("c_lactancia"));
                    TfPeso.setText(conexion.getRs().getString("peso"));
                    CodigoVaca.setText(vAux.getVcod());
                     X.setVisible(false);
                    NoPerteneceAlPlantel.setVisible(false);
                    Bien.setVisible(false);
                    
                }
            }catch(SQLException ex)
            {
                System.out.println(ex);
            }
    }//GEN-LAST:event_ListaVacasValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListadoDeVacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListadoDeVacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListadoDeVacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListadoDeVacas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListadoDeVacas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bien;
    private javax.swing.JTextField CodigoVaca;
    private javax.swing.JList<String> ListaVacas;
    private javax.swing.JLabel NoPerteneceAlPlantel;
    private javax.swing.JTextField TfLactancias;
    private javax.swing.JTextField TfPeso;
    private javax.swing.JTextField TfRaza;
    private javax.swing.JLabel X;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
